version: '3.8'
services:
  irondome:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: irondoma
    restart: unless-stopped
    tty: true
    ports:
      - 4243:4243
    volumes:
      - ./shared/log:/var/log/irondome
