from debian:stable-slim

WORKDIR /usr/src/iron

COPY sshd_config /etc/ssh/sshd_config

RUN useradd -m iron 
RUN echo "iron:iron" | chpasswd
RUN apt-get update && apt-get install openssh-server net-tools -y
RUN apt-get install vim python3 python3-pip python3-dev -y
RUN pip install --upgrade pip
RUN pip install resource psutil Observer watchdog

ENTRYPOINT service ssh restart; tail -f /dev/null
EXPOSE 4243